version: '3.8'

services:
  # 8080
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
    networks:
      - microservices-net
    restart: unless-stopped

  # 8081
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped

  # 8082
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - microservices-net
    restart: unless-stopped

  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - microservices-net
    restart: unless-stopped

# -- --- - -- - - - - --- -
networks:
  microservices-net:
    driver: bridge